[package]
name = "oia-core"
description = "Engine library for Óia."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
ulid = "1"
url = "2"
sha2 = "0.10"
hex = "0.4"
fs2 = "0.4"
anyhow = "1"
imagesize = "=0.14.0"
nom-exif = "=3.6.2"
rusqlite = { version = "0.32", features = ["bundled", "trace"] }
rustix = { version = "1", features = ["fs"] }
thiserror = "1"
unicode-casefold = "0.2"
uniffi = "0.29"
zip = { version = "2.4", default-features = false, features = ["deflate"] }
plist = "1"
time = { version = "0.3", features = ["parsing", "formatting"] }
tempfile = "3"
reqwest = { version = "0.13", features = ["blocking", "brotli", "deflate", "gzip"] }

[dev-dependencies]
proptest = "1"
